version: '3'
services:
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # ports:
    #   - "3306:3306"
    #volumes:
    #  - "/var/dev/data/mysql/slvae/data:/var/lib/mysql"
    #  - "/etc/localtime:/etc/localtime"
    #  - "/etc/mysql:/etc/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
